# file: nginx/tasks/modules/http_echo_module.yml
# configure flag: --add-module=/tmp/nginx_echo

- name: Nginx Install | Modules | Download the http_echo_module source
  get_url:
    url: "{{nginx_echo_url}}"
    dest: "/tmp/nginx-echo-module-{{nginx_echo_version}}.tar.gz"

- name: Nginx Install | Modules | Unpack the http_echo_module source
  command: "tar -xvzf /tmp/nginx-echo-module-{{nginx_echo_version}}.tar.gz"
  args:
    chdir:   "/tmp"
    creates: "/tmp/echo-nginx-module-{{nginx_echo_version}}"
